# Generated by Django 4.0.3 on 2022-04-11 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название определённой категории для слов.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(help_text='Enter english word here.', max_length=100)),
                ('transcript', models.CharField(blank=True, help_text='Enter transcription of word here (optional).', max_length=150, null=True)),
                ('rus_word', models.CharField(help_text='Enter russian translate.', max_length=200)),
                ('exemp', models.TextField(blank=True, help_text='Enter examples for word (opt.).', null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(help_text='Select a category', to='manager.category')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
